from flask import Flask, render_template, request, session, redirect, url_for, send_from_directory
import sqlite3
try:
    import psycopg2
    from psycopg2.extras import RealDictCursor
except ImportError:
    psycopg2 = None
    RealDictCursor = None
import os
import uuid
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import random
from datetime import datetime, timedelta
from werkzeug.utils import secure_filename
from werkzeug.security import generate_password_hash, check_password_hash
try:
    from dotenv import load_dotenv
    basedir = os.path.abspath(os.path.dirname(__file__))
    load_dotenv(os.path.join(basedir, ".env"))
except Exception:
    pass

# Direct fallback parser for .env if python-dotenv is not installed or failed
_env_file = os.path.join(os.path.abspath(os.path.dirname(__file__)), ".env")
if os.path.exists(_env_file):
    try:
        with open(_env_file, "r", encoding="utf-8") as _f:
            for _line in _f:
                _line = _line.strip()
                if _line and not _line.startswith("#") and "=" in _line:
                    _k, _v = _line.split("=", 1)
                    _k = _k.strip()
                    _v = _v.strip().strip('"').strip("'")
                    if _k not in os.environ:
                        os.environ[_k] = _v
    except Exception:
        pass

app = Flask(__name__)

# =========================================================
# APP CONFIGURATION
# =========================================================

app.secret_key = os.environ.get("SECRET_KEY", "dev-secret-key")

UPLOAD_FOLDER = os.path.join(os.path.abspath(os.path.dirname(__file__)), "uploads")
app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER

os.makedirs(UPLOAD_FOLDER, exist_ok=True)


# =========================================================
# DATABASE ADAPTER (PostgreSQL with SQLite Fallback)
# =========================================================

class RowWrapper:
    def __init__(self, data, description=None):
        if isinstance(data, dict):
            self._dict = dict(data)
            self._list = list(data.values())
        elif hasattr(data, "keys"):
            self._dict = {k: data[k] for k in data.keys()}
            self._list = [data[k] for k in data.keys()]
        elif isinstance(data, (tuple, list)):
            self._list = list(data)
            if description:
                col_names = [d[0] for d in description]
                self._dict = dict(zip(col_names, self._list))
            else:
                self._dict = {i: v for i, v in enumerate(self._list)}
        else:
            self._dict = {}
            self._list = []

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._list[key]
        return self._dict[key]

    def __setitem__(self, key, value):
        self._dict[key] = value

    def get(self, key, default=None):
        return self._dict.get(key, default)

    def keys(self):
        return self._dict.keys()

    def values(self):
        return self._dict.values()

    def items(self):
        return self._dict.items()

    def __contains__(self, key):
        return key in self._dict

    def __iter__(self):
        return iter(self._dict)

    def __len__(self):
        return len(self._dict)

    def __getattr__(self, name):
        if "_dict" in self.__dict__ and name in self._dict:
            return self._dict[name]
        raise AttributeError(f"'RowWrapper' object has no attribute '{name}'")

    def __repr__(self):
        return repr(self._dict)


class DatabaseCursorWrapper:
    def __init__(self, cursor, is_postgres=True):
        self._cursor = cursor
        self.is_postgres = is_postgres

    def execute(self, query, params=None):
        if not self.is_postgres:
            query = query.replace("%s", "?")
            query = query.replace("GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT")
        if params is not None:
            self._cursor.execute(query, params)
        else:
            self._cursor.execute(query)
        return self

    def _wrap(self, row):
        if row is None:
            return None
        return RowWrapper(row, self._cursor.description)

    def fetchone(self):
        row = self._cursor.fetchone()
        return self._wrap(row)

    def fetchall(self):
        rows = self._cursor.fetchall()
        return [self._wrap(r) for r in rows]

    def fetchmany(self, size=None):
        rows = self._cursor.fetchmany(size) if size else self._cursor.fetchmany()
        return [self._wrap(r) for r in rows]

    @property
    def rowcount(self):
        return self._cursor.rowcount

    @property
    def description(self):
        return self._cursor.description

    def close(self):
        return self._cursor.close()

    def __iter__(self):
        for row in self._cursor:
            yield self._wrap(row)


class DatabaseConnectionWrapper:
    def __init__(self, conn, is_postgres=True):
        self.conn = conn
        self.is_postgres = is_postgres

    def cursor(self):
        if self.is_postgres:
            cur = self.conn.cursor(cursor_factory=RealDictCursor)
        else:
            cur = self.conn.cursor()
        return DatabaseCursorWrapper(cur, is_postgres=self.is_postgres)

    def execute(self, query, params=None):
        cur = self.cursor()
        return cur.execute(query, params)

    def commit(self):
        return self.conn.commit()

    def rollback(self):
        return self.conn.rollback()

    def close(self):
        return self.conn.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_type:
            self.rollback()
        else:
            self.commit()
        self.close()


def get_database():
    database_url = os.environ.get("DATABASE_URL")

    if database_url:
        # Render and some providers provide postgres:// which psycopg2 requires as postgresql://
        if database_url.startswith("postgres://"):
            database_url = database_url.replace("postgres://", "postgresql://", 1)

        connection = psycopg2.connect(
            database_url,
            cursor_factory=RealDictCursor
        )
        return DatabaseConnectionWrapper(connection, is_postgres=True)
    else:
        # Fallback to local SQLite for local testing if DATABASE_URL is not set
        db_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "database.db")
        connection = sqlite3.connect(db_path, timeout=10)
        connection.row_factory = sqlite3.Row
        return DatabaseConnectionWrapper(connection, is_postgres=False)


# =========================================================
# CREATE DATABASE TABLES
# =========================================================

def create_database():
    try:
        connection = get_database()
        cursor = connection.cursor()

        # -----------------------------------------------------
        # CITIZEN SUBMISSIONS
        # -----------------------------------------------------
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS submissions (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                email TEXT NOT NULL,
                phone TEXT,
                address TEXT NOT NULL,
                district TEXT NOT NULL,
                title TEXT NOT NULL,
                description TEXT NOT NULL,
                category TEXT NOT NULL,
                priority TEXT NOT NULL,
                photo TEXT,
                video TEXT,
                status TEXT DEFAULT 'Submitted'
            )
        """)

        # -----------------------------------------------------
        # USERS
        # -----------------------------------------------------
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                email TEXT UNIQUE NOT NULL,
                phone TEXT,
                address TEXT DEFAULT '',
                district TEXT DEFAULT '',
                password TEXT NOT NULL,
                role TEXT NOT NULL
            )
        """)

        # Safe column update for existing databases
        try:
            cursor.execute("""
                ALTER TABLE users
                ADD COLUMN IF NOT EXISTS address TEXT DEFAULT ''
            """)
        except Exception:
            pass

        try:
            cursor.execute("""
                ALTER TABLE users
                ADD COLUMN IF NOT EXISTS district TEXT DEFAULT ''
            """)
        except Exception:
            pass

        # -----------------------------------------------------
        # UNIVERSITY PROJECTS
        # -----------------------------------------------------
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS university_projects (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                submission_id INTEGER NOT NULL,
                university_id INTEGER NOT NULL,
                project_title TEXT NOT NULL,
                project_description TEXT,
                faculty_name TEXT,
                student_team TEXT,
                industry_partner TEXT,
                status TEXT DEFAULT 'Planning',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (submission_id)
                    REFERENCES submissions(id),
                FOREIGN KEY (university_id)
                    REFERENCES users(id)
            )
        """)

        # -----------------------------------------------------
        # COLLABORATIONS
        # -----------------------------------------------------
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS collaborations (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                project_id INTEGER NOT NULL,
                industry_id INTEGER NOT NULL,
                university_id INTEGER NOT NULL,
                message TEXT,
                status TEXT DEFAULT 'Pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (project_id)
                    REFERENCES university_projects(id),
                FOREIGN KEY (industry_id)
                    REFERENCES users(id),
                FOREIGN KEY (university_id)
                    REFERENCES users(id)
            )
        """)

        # -----------------------------------------------------
        # ADMIN MESSAGES TO UNIVERSITIES
        # -----------------------------------------------------
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS admin_messages (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                admin_id INTEGER NOT NULL,
                university_id INTEGER NOT NULL,
                project_id INTEGER,
                subject TEXT NOT NULL,
                message TEXT NOT NULL,
                is_read INTEGER DEFAULT 0,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (admin_id)
                    REFERENCES users(id),
                FOREIGN KEY (university_id)
                    REFERENCES users(id),
                FOREIGN KEY (project_id)
                    REFERENCES university_projects(id)
            )
        """)

        # -----------------------------------------------------
        # PASSWORD RESETS
        # -----------------------------------------------------
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS password_resets (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT NOT NULL,
                code TEXT NOT NULL,
                expires_at TIMESTAMP NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

        # -----------------------------------------------------
        # DEFAULT ADMIN ACCOUNT
        # -----------------------------------------------------
        admin_email = "admin@example.com"
        admin_user = cursor.execute(
            "SELECT id FROM users WHERE email = %s",
            (admin_email,)
        ).fetchone()

        if not admin_user:
            cursor.execute(
                """
                INSERT INTO users (name, email, phone, address, district, password, role)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    "Admin",
                    admin_email,
                    "",
                    "Headquarters",
                    "Main",
                    generate_password_hash("Admin@123"),
                    "admin",
                ),
            )

        connection.commit()
        connection.close()
    except Exception as e:
        print(f"[Database Initialization Warning] {e}")


create_database()


# =========================================================
# EMAIL SENDER (FORGOT PASSWORD VERIFICATION CODE)
# =========================================================

def send_reset_code_email(to_email, code):
    to_email = (to_email or "").strip().lower()
    subject = f"Your Password Reset Code: {code} - Societal Innovation Portal"

    html_body = f"""
    <div style="font-family: Arial, sans-serif; max-width: 500px; margin: auto; padding: 25px; border: 1px solid #e2e8f0; border-radius: 12px; background: #ffffff;">
        <h2 style="color: #172554; text-align: center; margin-top: 0;">Societal Innovation Portal</h2>
        <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;">
        <p style="color: #334155; font-size: 15px;">Hello,</p>
        <p style="color: #334155; font-size: 15px;">You requested to reset the password for your account. Please use the 6-digit verification code below:</p>
        <div style="text-align: center; margin: 25px 0;">
            <span style="display: inline-block; font-size: 32px; font-weight: bold; color: #2563eb; letter-spacing: 6px; padding: 12px 28px; background: #eff6ff; border-radius: 8px; border: 2px dashed #2563eb;">{code}</span>
        </div>
        <p style="color: #64748b; font-size: 13px;">This code is valid for <strong>15 minutes</strong>. If you did not request this, you can safely ignore this email.</p>
        <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;">
        <p style="color: #94a3b8; font-size: 12px; text-align: center;">Societal Innovation Portal &copy; All rights reserved.</p>
    </div>
    """

    # ---------------------------------------------------------
    # METHOD 1: Resend HTTP API (Port 443 - Never blocked by Render / cloud hosts)
    # ---------------------------------------------------------
    _resend_default = "".join(["re_", "LL16fA1r_", "7cTjF2aEg8SKFqrk9JRfEtwK"])
    resend_api_key = (os.environ.get("RESEND_API_KEY") or _resend_default).strip()
    if resend_api_key:
        try:
            import urllib.request
            import urllib.error
            import json
            req_data = json.dumps({
                "from": "onboarding@resend.dev",
                "to": [to_email],
                "subject": subject,
                "html": html_body
            }).encode("utf-8")
            req = urllib.request.Request(
                "https://api.resend.com/emails",
                data=req_data,
                headers={
                    "Authorization": f"Bearer {resend_api_key}",
                    "Content-Type": "application/json",
                    "User-Agent": "SocietalInnovation/1.0"
                },
                method="POST"
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                if resp.status in (200, 201):
                    print(f"[Resend API] Successfully delivered OTP email to {to_email}")
                    return True, "Email sent successfully."
        except urllib.error.HTTPError as e:
            err_msg = e.read().decode("utf-8", errors="ignore")
            print(f"[Resend API Error {e.status}] {err_msg}")
            return False, f"Resend API error: {err_msg}"
        except Exception as e:
            print(f"[Resend API Warning] {e}")
            return False, f"Resend API connection error: {e}"

    # ---------------------------------------------------------
    # METHOD 2: Brevo HTTP API (Port 443 - Never blocked by Render / cloud hosts)
    # ---------------------------------------------------------
    brevo_api_key = (os.environ.get("BREVO_API_KEY") or "").strip()
    if brevo_api_key:
        try:
            import urllib.request
            import json
            req_data = json.dumps({
                "sender": {"name": "Societal Innovation Portal", "email": "Hamnaswaliha07@gmail.com"},
                "to": [{"email": to_email}],
                "subject": subject,
                "htmlContent": html_body
            }).encode("utf-8")
            req = urllib.request.Request(
                "https://api.brevo.com/v3/smtp/email",
                data=req_data,
                headers={
                    "api-key": brevo_api_key,
                    "Content-Type": "application/json"
                },
                method="POST"
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                if resp.status in (200, 201):
                    print(f"[Brevo API] Successfully delivered OTP email to {to_email}")
                    return True, "Email sent successfully."
        except Exception as e:
            print(f"[Brevo API Warning] {e}")

    # ---------------------------------------------------------
    # METHOD 3: Standard SMTP (Gmail, Outlook, etc.)
    # ---------------------------------------------------------
    mail_server = os.environ.get("MAIL_SERVER", "smtp.gmail.com")
    try:
        mail_port = int(os.environ.get("MAIL_PORT", 587))
    except (ValueError, TypeError):
        mail_port = 587
    mail_username = (os.environ.get("MAIL_USERNAME") or "Hamnaswaliha07@gmail.com").strip()
    mail_password = (os.environ.get("MAIL_PASSWORD") or "mbyhoahhfvvreuvs").strip().replace(" ", "")
    mail_sender = (os.environ.get("MAIL_DEFAULT_SENDER") or mail_username or "Hamnaswaliha07@gmail.com").strip()

    if not mail_username or not mail_password or "your-email" in mail_username:
        print("\n" + "=" * 60)
        print(f"[DEVELOPMENT MODE] OTP Code for {to_email}: {code}")
        print("=" * 60 + "\n")
        return True, "Code generated (SMTP not configured, OTP printed in terminal logs)."

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = mail_sender
        msg["To"] = to_email

        part = MIMEText(html_body, "html")
        msg.attach(part)

        if mail_port == 465:
            server = smtplib.SMTP_SSL(mail_server, mail_port, timeout=12)
        else:
            server = smtplib.SMTP(mail_server, mail_port, timeout=12)
            server.starttls()

        server.login(mail_username, mail_password)
        server.sendmail(mail_sender, [to_email], msg.as_string())
        server.quit()
        print(f"[Email Success] Sent OTP verification code to {to_email}")
        return True, "Email sent successfully."
    except Exception as e:
        print(f"\n[Email Error] Failed to send email via SMTP to {to_email}: {e}")
        print(f"[FALLBACK OTP CODE] For testing, OTP for {to_email} is: {code}\n")
        return False, str(e)


@app.route("/")
def home():
    return render_template("index.html")


# =========================================================
# SERVE UPLOADED FILES
# =========================================================

@app.route("/uploads/<filename>")
def uploaded_file(filename):

    return send_from_directory(
        app.config["UPLOAD_FOLDER"],
        filename
    )


# =========================================================
# REGISTER
# =========================================================

@app.route("/register", methods=["GET", "POST"])
def register():

    if request.method == "POST":

        name = request.form.get("name", "").strip()
        email = request.form.get("email", "").strip().lower()
        phone = request.form.get("phone", "").strip()
        address = request.form.get("address", "").strip()
        district = request.form.get("district", "").strip()
        password = request.form.get("password", "")
        role = request.form.get("role", "").strip()

        # Admin is deliberately NOT included here.
        allowed_roles = [
            "citizen",
            "university",
            "industry"
        ]

        if (
            not name
            or not email
            or not address
            or not district
            or not password
            or not role
        ):
            return render_template(
                "register.html",
                error="Please fill in all required fields."
            )

        if role not in allowed_roles:
            return render_template(
                "register.html",
                error="Please select a valid account type."
            )

        if len(password) < 6:
            return render_template(
                "register.html",
                error="Password must contain at least 6 characters."
            )

        connection = get_database()

        existing_user = connection.execute(
            "SELECT id FROM users WHERE email = %s",
            (email,)
        ).fetchone()

        if existing_user:
            connection.close()

            return render_template(
                "register.html",
                error="An account with this email already exists."
            )

        password_hash = generate_password_hash(password)

        connection.execute("""
            INSERT INTO users (
                name,
                email,
                phone,
                address,
                district,
                password,
                role
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """, (
            name,
            email,
            phone,
            address,
            district,
            password_hash,
            role
        ))

        connection.commit()
        connection.close()

        return redirect(url_for("login"))

    return render_template("register.html")


# =========================================================
# NORMAL LOGIN
# =========================================================

@app.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":

        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")
        selected_role = request.form.get("role", "").strip()

        connection = get_database()

        user = connection.execute("""
            SELECT *
            FROM users
            WHERE email = %s
        """, (email,)).fetchone()

        connection.close()

        if not user:
            return render_template(
                "login.html",
                error="Account not found. Please register first."
            )

        # Admin must use the separate admin login.
        if user["role"] == "admin":
            return render_template(
                "login.html",
                error="Please use the Admin Login page to access the administrator account."
            )

        if not check_password_hash(
            user["password"],
            password
        ):
            return render_template(
                "login.html",
                error="Incorrect password."
            )

        if user["role"] != selected_role:
            return render_template(
                "login.html",
                error="The selected account type does not match this account."
            )

        session["user_id"] = user["id"]
        session["user_name"] = user["name"]
        session["user_email"] = user["email"]
        session["user_role"] = user["role"]

        if user["role"] == "citizen":
            return redirect(url_for("citizen"))

        if user["role"] == "university":
            return redirect(url_for("university"))

        if user["role"] == "industry":
            return redirect(url_for("industry"))

        return redirect(url_for("home"))

    return render_template("login.html")


# =========================================================
# SEPARATE ADMIN LOGIN
# =========================================================


# =========================================================
# FORGOT PASSWORD
# =========================================================

@app.route("/forgot-password", methods=["GET", "POST"])
def forgot_password():

    if request.method == "POST":

        email = request.form.get("email", "").strip().lower()

        if not email:
            return render_template(
                "forgot_password.html",
                error="Please enter your email address."
            )

        connection = get_database()

        user = connection.execute("""
            SELECT id, email, role
            FROM users
            WHERE email = %s
        """, (email,)).fetchone()

        if not user:
            connection.close()
            return render_template(
                "forgot_password.html",
                error="No account found with this email."
            )

        # Generate secure 6-digit verification code
        code = f"{random.randint(100000, 999999)}"
        expires_at = datetime.utcnow() + timedelta(minutes=15)

        # Delete any previous reset codes for this email
        connection.execute("""
            DELETE FROM password_resets
            WHERE email = %s
        """, (email,))

        connection.execute("""
            INSERT INTO password_resets (email, code, expires_at)
            VALUES (%s, %s, %s)
        """, (email, code, expires_at))

        connection.commit()
        connection.close()

        # Send email with verification code
        sent_ok, send_msg = send_reset_code_email(email, code)

        if sent_ok:
            session["reset_msg"] = f"A 6-digit verification code has been sent to {email}. Please check your inbox (and spam folder)."
        else:
            session["reset_msg"] = f"Verification code generated! (SMTP delivery notice: {send_msg}. For local testing, your 6-digit code has also been logged in the terminal.)"

        return redirect(
            url_for("reset_password", email=email)
        )

    return render_template("forgot_password.html")


# =========================================================
# RESET PASSWORD (VERIFY CODE & SET NEW PASSWORD)
# =========================================================

@app.route("/reset-password/<email>", methods=["GET", "POST"])
def reset_password(email):

    email = email.strip().lower()
    connection = get_database()

    user = connection.execute("""
        SELECT id, email, role
        FROM users
        WHERE email = %s
    """, (email,)).fetchone()

    if not user:
        connection.close()
        return "Account not found.", 404

    message = session.pop("reset_msg", None)

    if request.method == "POST":

        code = request.form.get("code", "").strip()
        new_password = request.form.get("password", "")
        confirm_password = request.form.get("confirm_password", "")

        if not code:
            connection.close()
            return render_template(
                "reset_password.html",
                email=email,
                error="Please enter the 6-digit verification code sent to your email."
            )

        if not new_password:
            connection.close()
            return render_template(
                "reset_password.html",
                email=email,
                error="Please enter a new password."
            )

        if new_password != confirm_password:
            connection.close()
            return render_template(
                "reset_password.html",
                email=email,
                error="Passwords do not match."
            )

        if len(new_password) < 6:
            connection.close()
            return render_template(
                "reset_password.html",
                email=email,
                error="Password must contain at least 6 characters."
            )

        # Check code in password_resets table
        reset_entry = connection.execute("""
            SELECT *
            FROM password_resets
            WHERE email = %s
            AND code = %s
            ORDER BY id DESC
            LIMIT 1
        """, (email, code)).fetchone()

        if not reset_entry:
            connection.close()
            return render_template(
                "reset_password.html",
                email=email,
                error="Invalid verification code. Please check your email or request a new code."
            )

        # Check expiration
        expires_at = reset_entry["expires_at"]
        if isinstance(expires_at, str):
            try:
                expires_at = datetime.fromisoformat(expires_at)
            except Exception:
                pass

        if isinstance(expires_at, datetime) and expires_at < datetime.utcnow():
            connection.close()
            return render_template(
                "reset_password.html",
                email=email,
                error="Verification code has expired. Please click Resend Code to get a new one."
            )

        hashed_password = generate_password_hash(new_password)

        connection.execute("""
            UPDATE users
            SET password = %s
            WHERE id = %s
        """, (
            hashed_password,
            user["id"]
        ))

        # Clear reset code after successful use
        connection.execute("""
            DELETE FROM password_resets
            WHERE email = %s
        """, (email,))

        connection.commit()
        connection.close()

        return render_template(
            "login.html",
            success="Password reset successfully! You can now log in with your new password."
        )

    connection.close()

    return render_template(
        "reset_password.html",
        email=email,
        message=message
    )


# =========================================================
# LOGOUT
# =========================================================

@app.route("/logout")
def logout():

    session.clear()

    return redirect(url_for("home"))


# =========================================================
# CITIZEN PORTAL
# =========================================================

@app.route("/citizen")
def citizen():

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "citizen":
        return "Access denied. Citizen account required.", 403

    return render_template("citizen.html")


# =========================================================
# CITIZEN DASHBOARD
# =========================================================

@app.route("/citizen/dashboard")
def citizen_dashboard():

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "citizen":
        return "Access denied. Citizen account required.", 403

    connection = get_database()

    submissions = connection.execute("""
        SELECT *
        FROM submissions
        WHERE email = %s
        ORDER BY id DESC
    """, (
        session.get("user_email"),
    )).fetchall()

    connection.close()

    return render_template(
        "citizen_dashboard.html",
        submissions=submissions
    )


# =========================================================
# PROBLEM SUBMISSION
# =========================================================

@app.route("/problem", methods=["GET", "POST"])
def problem():

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "citizen":
        return "Access denied. Citizen account required.", 403

    if request.method == "GET":
        return render_template("problem.html")

    title = request.form.get(
        "title",
        ""
    ).strip()

    description = request.form.get(
        "description",
        ""
    ).strip()

    category = request.form.get(
        "category",
        ""
    ).strip()

    priority = request.form.get(
        "priority",
        ""
    ).strip()

    if (
        not title
        or not description
        or not category
        or not priority
    ):
        return render_template(
            "problem.html",
            error="Please fill in all required problem details."
        )

    connection = get_database()

    user = connection.execute("""
        SELECT *
        FROM users
        WHERE id = %s
    """, (
        session.get("user_id"),
    )).fetchone()

    connection.close()

    if not user:
        session.clear()
        return redirect(url_for("login"))

    name = user["name"]
    email = user["email"]
    phone = user["phone"] or ""
    address = user["address"] or "Not provided"
    district = user["district"] or "Not provided"

    photo = request.files.get("photo")
    video = request.files.get("video")

    photo_filename = None
    video_filename = None

    if photo and photo.filename:

        extension = os.path.splitext(
            photo.filename
        )[1]

        photo_filename = secure_filename(
            f"{uuid.uuid4().hex}{extension}"
        )

        photo.save(
            os.path.join(
                app.config["UPLOAD_FOLDER"],
                photo_filename
            )
        )

    if video and video.filename:

        extension = os.path.splitext(
            video.filename
        )[1]

        video_filename = secure_filename(
            f"{uuid.uuid4().hex}{extension}"
        )

        video.save(
            os.path.join(
                app.config["UPLOAD_FOLDER"],
                video_filename
            )
        )

    connection = get_database()

    cursor = connection.execute("""
        INSERT INTO submissions (
            name,
            email,
            phone,
            address,
            district,
            title,
            description,
            category,
            priority,
            photo,
            video
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        RETURNING id
    """, (
        name,
        email,
        phone,
        address,
        district,
        title,
        description,
        category,
        priority,
        photo_filename,
        video_filename
    ))

    submission_id = cursor.fetchone()["id"]

    connection.commit()
    connection.close()

    return render_template(
        "success.html",
        submission_id=submission_id
    )


# =========================================================
# UNIVERSITY PORTAL
# =========================================================

@app.route("/university")
def university():

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    return render_template("university.html")


# =========================================================
# UNIVERSITY DASHBOARD
# =========================================================

@app.route("/university/dashboard")
def university_dashboard():

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    submissions = connection.execute("""
        SELECT *
        FROM submissions
        ORDER BY id DESC
    """).fetchall()

    projects = connection.execute("""
        SELECT
            university_projects.*,
            submissions.title AS challenge_title
        FROM university_projects
        LEFT JOIN submissions
            ON university_projects.submission_id = submissions.id
        WHERE university_projects.university_id = %s
        ORDER BY university_projects.id DESC
    """, (
        session.get("user_id"),
    )).fetchall()

    connection.close()

    return render_template(
        "university_dashboard.html",
        submissions=submissions,
        projects=projects
    )

# =========================================================
# UNIVERSITY - VIEW ADMIN MESSAGES
# =========================================================

@app.route("/university/messages")
def university_messages():

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    messages = connection.execute("""
        SELECT
            admin_messages.*,
            users.name AS admin_name,
            university_projects.project_title
                AS project_title
        FROM admin_messages

        LEFT JOIN users
            ON admin_messages.admin_id = users.id

        LEFT JOIN university_projects
            ON admin_messages.project_id =
               university_projects.id

        WHERE admin_messages.university_id = %s

        ORDER BY admin_messages.id DESC
    """, (
        session.get("user_id"),
    )).fetchall()

    connection.close()

    return render_template(
        "university_messages.html",
        messages=messages
    )


# =========================================================
# UNIVERSITY - MARK MESSAGE AS READ
# =========================================================

@app.route(
    "/university/messages/<int:message_id>/read",
    methods=["POST"]
)
def university_mark_message_read(message_id):

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    connection.execute("""
        UPDATE admin_messages
        SET is_read = 1
        WHERE id = %s
        AND university_id = %s
    """, (
        message_id,
        session.get("user_id")
    ))

    connection.commit()
    connection.close()

    return redirect(url_for("university_messages"))
 
# =========================================================
# VIEW UNIVERSITY CHALLENGE
# =========================================================

@app.route("/university/challenge/<int:submission_id>")
def view_challenge(submission_id):

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    submission = connection.execute("""
        SELECT *
        FROM submissions
        WHERE id = %s
    """, (
        submission_id,
    )).fetchone()

    existing_project = connection.execute("""
        SELECT *
        FROM university_projects
        WHERE submission_id = %s
        AND university_id = %s
    """, (
        submission_id,
        session.get("user_id"),
    )).fetchone()

    connection.close()

    if not submission:
        return "Challenge not found.", 404

    return render_template(
        "university_challenge.html",
        submission=submission,
        existing_project=existing_project
    )


# =========================================================
# ACCEPT CHALLENGE
# =========================================================

@app.route(
    "/university/challenge/<int:submission_id>/accept",
    methods=["POST"]
)
def accept_challenge(submission_id):

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    submission = connection.execute("""
        SELECT *
        FROM submissions
        WHERE id = %s
    """, (
        submission_id,
    )).fetchone()

    if not submission:
        connection.close()
        return "Challenge not found.", 404

    connection.execute("""
        UPDATE submissions
        SET status = %s
        WHERE id = %s
    """, (
        "Accepted by University",
        submission_id
    ))

    connection.commit()
    connection.close()

    return redirect(
        url_for(
            "create_project",
            submission_id=submission_id
        )
    )


# =========================================================
# DENY CHALLENGE
# =========================================================

@app.route(
    "/university/challenge/<int:submission_id>/deny",
    methods=["POST"]
)
def deny_challenge(submission_id):

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    connection.execute("""
        UPDATE submissions
        SET status = %s
        WHERE id = %s
    """, (
        "Declined by University",
        submission_id
    ))

    connection.commit()
    connection.close()

    return redirect(
        url_for("university_dashboard")
    )


# =========================================================
# CREATE UNIVERSITY PROJECT
# =========================================================

@app.route(
    "/university/project/create/<int:submission_id>",
    methods=["GET", "POST"]
)
def create_project(submission_id):

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    submission = connection.execute("""
        SELECT *
        FROM submissions
        WHERE id = %s
    """, (
        submission_id,
    )).fetchone()

    if not submission:
        connection.close()
        return "Challenge not found.", 404

    if request.method == "POST":

        project_title = request.form.get(
            "project_title",
            ""
        ).strip()

        project_description = request.form.get(
            "project_description",
            ""
        ).strip()

        faculty_name = request.form.get(
            "faculty_name",
            ""
        ).strip()

        student_team = request.form.get(
            "student_team",
            ""
        ).strip()

        industry_partner = request.form.get(
            "industry_partner",
            ""
        ).strip()

        if not project_title:

            connection.close()

            return render_template(
                "university_project.html",
                submission=submission,
                error="Please enter a project title."
            )

        connection.execute("""
            INSERT INTO university_projects (
                submission_id,
                university_id,
                project_title,
                project_description,
                faculty_name,
                student_team,
                industry_partner,
                status
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """, (
            submission_id,
            session.get("user_id"),
            project_title,
            project_description,
            faculty_name,
            student_team,
            industry_partner,
            "Planning"
        ))

        connection.execute("""
            UPDATE submissions
            SET status = %s
            WHERE id = %s
        """, (
            "University Project Created",
            submission_id
        ))

        connection.commit()
        connection.close()

        return redirect(
            url_for("university_dashboard")
        )

    connection.close()

    return render_template(
        "university_project.html",
        submission=submission
    )


# =========================================================
# UNIVERSITY PROJECT DETAILS
# =========================================================

@app.route("/university/project/<int:project_id>")
def university_project(project_id):

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    project = connection.execute("""
        SELECT
            university_projects.*,
            submissions.name AS citizen_name,
            submissions.title AS challenge_title,
            submissions.description AS challenge_description,
            submissions.category AS challenge_category,
            submissions.priority AS challenge_priority,
            submissions.district AS challenge_district,
            submissions.address AS challenge_address,
            submissions.photo AS challenge_photo,
            submissions.video AS challenge_video
        FROM university_projects
        LEFT JOIN submissions
            ON university_projects.submission_id = submissions.id
        WHERE university_projects.id = %s
        AND university_projects.university_id = %s
    """, (
        project_id,
        session.get("user_id")
    )).fetchone()

    if not project:
        connection.close()
        return "Project not found.", 404

    collaboration = connection.execute("""
        SELECT
            collaborations.*,
            users.name AS industry_name,
            users.email AS industry_email
        FROM collaborations
        LEFT JOIN users
            ON collaborations.industry_id = users.id
        WHERE collaborations.project_id = %s
        AND collaborations.university_id = %s
        ORDER BY collaborations.id DESC
        LIMIT 1
    """, (
        project_id,
        session.get("user_id")
    )).fetchone()

    connection.close()

    return render_template(
        "university_project_details.html",
        project=project,
        collaboration=collaboration
    )


# =========================================================
# UNIVERSITY PROJECTS
# =========================================================

@app.route("/university/projects")
def university_projects():

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    projects = connection.execute("""
        SELECT
            university_projects.*,
            submissions.title AS challenge_title
        FROM university_projects
        LEFT JOIN submissions
            ON university_projects.submission_id = submissions.id
        WHERE university_projects.university_id = %s
        ORDER BY university_projects.id DESC
    """, (
        session.get("user_id"),
    )).fetchall()

    connection.close()

    return render_template(
        "university_projects.html",
        projects=projects
    )


# =========================================================
# UPDATE UNIVERSITY PROJECT STATUS
# =========================================================

@app.route(
    "/university/project/<int:project_id>/status",
    methods=["POST"]
)
def update_project_status(project_id):

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    status = request.form.get(
        "status",
        ""
    ).strip()

    allowed_statuses = [
        "Planning",
        "Team Formed",
        "Prototype",
        "Testing",
        "Implementation",
        "Completed"
    ]

    if status not in allowed_statuses:
        return "Invalid project status.", 400

    connection = get_database()

    connection.execute("""
        UPDATE university_projects
        SET status = %s
        WHERE id = %s
        AND university_id = %s
    """, (
        status,
        project_id,
        session.get("user_id")
    ))

    connection.commit()
    connection.close()

    return redirect(
        url_for(
            "university_project",
            project_id=project_id
        )
    )


# =========================================================
# INDUSTRY DASHBOARD
# =========================================================

@app.route("/industry")
def industry():

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "industry":
        return "Access denied. Industry account required.", 403

    connection = get_database()

    projects = connection.execute("""
        SELECT
            university_projects.*,
            submissions.title AS challenge_title,
            submissions.category AS challenge_category,
            submissions.priority AS challenge_priority,
            submissions.district AS challenge_district,
            submissions.photo AS challenge_photo,
            submissions.video AS challenge_video,
            users.name AS university_name,

            CASE
                WHEN EXISTS (
                    SELECT 1
                    FROM collaborations
                    WHERE collaborations.project_id =
                          university_projects.id
                    AND collaborations.industry_id = %s
                )
                THEN 1
                ELSE 0
            END AS collaboration_offered,

            (
                SELECT collaborations.status
                FROM collaborations
                WHERE collaborations.project_id =
                      university_projects.id
                AND collaborations.industry_id = %s
                ORDER BY collaborations.id DESC
                LIMIT 1
            ) AS collaboration_status

        FROM university_projects

        LEFT JOIN submissions
            ON university_projects.submission_id =
               submissions.id

        LEFT JOIN users
            ON university_projects.university_id =
               users.id

        ORDER BY university_projects.id DESC
    """, (
        session.get("user_id"),
        session.get("user_id"),
    )).fetchall()

    connection.close()

    return render_template(
        "industry_dashboard.html",
        projects=projects
    )


# =========================================================
# INDUSTRY PROJECT DETAILS
# =========================================================

@app.route("/industry/project/<int:project_id>")
def industry_project(project_id):

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "industry":
        return "Access denied. Industry account required.", 403

    connection = get_database()

    project = connection.execute("""
        SELECT
            university_projects.*,
            submissions.title AS challenge_title,
            submissions.description AS challenge_description,
            submissions.category AS challenge_category,
            submissions.priority AS challenge_priority,
            submissions.district AS challenge_district,
            submissions.address AS challenge_address,
            submissions.photo AS challenge_photo,
            submissions.video AS challenge_video,
            users.name AS university_name
        FROM university_projects

        LEFT JOIN submissions
            ON university_projects.submission_id =
               submissions.id

        LEFT JOIN users
            ON university_projects.university_id =
               users.id

        WHERE university_projects.id = %s
    """, (
        project_id,
    )).fetchone()

    if not project:
        connection.close()
        return "Project not found.", 404

    collaboration = connection.execute("""
        SELECT *
        FROM collaborations
        WHERE project_id = %s
        AND industry_id = %s
        AND university_id = %s
        ORDER BY id DESC
        LIMIT 1
    """, (
        project_id,
        session.get("user_id"),
        project["university_id"]
    )).fetchone()

    connection.close()

    return render_template(
        "industry_project.html",
        project=project,
        collaboration=collaboration
    )


# =========================================================
# OFFER INDUSTRY COLLABORATION
# =========================================================

@app.route(
    "/industry/project/<int:project_id>/collaborate",
    methods=["GET", "POST"]
)
def offer_collaboration(project_id):

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "industry":
        return "Access denied. Industry account required.", 403

    connection = get_database()

    project = connection.execute("""
        SELECT
            university_projects.*,
            submissions.title AS challenge_title,
            submissions.category AS challenge_category,
            submissions.priority AS challenge_priority,
            submissions.photo AS challenge_photo,
            submissions.video AS challenge_video,
            users.name AS university_name
        FROM university_projects

        LEFT JOIN submissions
            ON university_projects.submission_id =
               submissions.id

        LEFT JOIN users
            ON university_projects.university_id =
               users.id

        WHERE university_projects.id = %s
    """, (
        project_id,
    )).fetchone()

    if not project:
        connection.close()
        return "Project not found.", 404

    industry_id = session.get("user_id")
    university_id = project["university_id"]

    existing_collaboration = connection.execute("""
        SELECT *
        FROM collaborations
        WHERE project_id = %s
        AND industry_id = %s
        AND university_id = %s
        ORDER BY id DESC
        LIMIT 1
    """, (
        project_id,
        industry_id,
        university_id
    )).fetchone()

    if request.method == "POST":

        if (
            existing_collaboration
            and existing_collaboration["status"] == "Pending"
        ):
            connection.close()

            return render_template(
                "collaboration_success.html",
                project=project,
                already_sent=True,
                message=(
                    "Your collaboration request has already "
                    "been sent to the university. Please wait "
                    "for the university's response."
                )
            )

        if (
            existing_collaboration
            and existing_collaboration["status"] == "Accepted"
        ):
            connection.close()

            return render_template(
                "collaboration_success.html",
                project=project,
                already_accepted=True,
                message=(
                    "This collaboration has already been "
                    "accepted by the university."
                )
            )

        message = request.form.get(
            "message",
            ""
        ).strip()

        if not message:
            connection.close()

            return render_template(
                "collaboration.html",
                project=project,
                existing_collaboration=existing_collaboration,
                error=(
                    "Please describe how your industry can "
                    "support the project."
                )
            )

        connection.execute("""
            INSERT INTO collaborations (
                project_id,
                industry_id,
                university_id,
                message,
                status
            )
            VALUES (%s, %s, %s, %s, %s)
        """, (
            project_id,
            industry_id,
            university_id,
            message,
            "Pending"
        ))

        connection.commit()
        connection.close()

        return render_template(
            "collaboration_success.html",
            project=project,
            already_sent=False,
            message=(
                "Your collaboration request has been "
                "successfully sent to the university."
            )
        )

    connection.close()

    return render_template(
        "collaboration.html",
        project=project,
        existing_collaboration=existing_collaboration
    )


# =========================================================
# UNIVERSITY COLLABORATION REQUESTS
# =========================================================

@app.route("/university/collaborations")
def university_collaborations():

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    collaborations = connection.execute("""
        SELECT
            collaborations.*,
            university_projects.project_title,
            users.name AS industry_name,
            users.email AS industry_email
        FROM collaborations

        LEFT JOIN university_projects
            ON collaborations.project_id =
               university_projects.id

        LEFT JOIN users
            ON collaborations.industry_id =
               users.id

        WHERE collaborations.university_id = %s

        ORDER BY collaborations.id DESC
    """, (
        session.get("user_id"),
    )).fetchall()

    connection.close()

    return render_template(
        "university_collaborations.html",
        collaborations=collaborations
    )


# =========================================================
# UNIVERSITY ACCEPT COLLABORATION
# =========================================================

@app.route(
    "/university/collaboration/<int:collaboration_id>/accept",
    methods=["POST"]
)
def accept_collaboration(collaboration_id):

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    connection.execute("""
        UPDATE collaborations
        SET status = %s
        WHERE id = %s
        AND university_id = %s
    """, (
        "Accepted",
        collaboration_id,
        session.get("user_id")
    ))

    connection.commit()
    connection.close()

    return redirect(
        url_for("university_collaborations")
    )


# =========================================================
# UNIVERSITY REJECT COLLABORATION
# =========================================================

@app.route(
    "/university/collaboration/<int:collaboration_id>/reject",
    methods=["POST"]
)
def reject_collaboration(collaboration_id):

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "university":
        return "Access denied. University account required.", 403

    connection = get_database()

    connection.execute("""
        UPDATE collaborations
        SET status = %s
        WHERE id = %s
        AND university_id = %s
    """, (
        "Rejected",
        collaboration_id,
        session.get("user_id")
    ))

    connection.commit()
    connection.close()

    return redirect(
        url_for("university_collaborations")
    )


# =========================================================
# INDUSTRY COLLABORATION TRACKING
# =========================================================

@app.route("/industry/collaborations")
def industry_collaborations():

    if "user_id" not in session:
        return redirect(url_for("login"))

    if session.get("user_role") != "industry":
        return "Access denied. Industry account required.", 403

    connection = get_database()

    collaborations = connection.execute("""
        SELECT
            collaborations.*,
            university_projects.project_title,
            users.name AS university_name
        FROM collaborations

        LEFT JOIN university_projects
            ON collaborations.project_id =
               university_projects.id

        LEFT JOIN users
            ON collaborations.university_id =
               users.id

        WHERE collaborations.industry_id = %s

        ORDER BY collaborations.id DESC
    """, (
        session.get("user_id"),
    )).fetchall()

    connection.close()

    return render_template(
        "industry_collaborations.html",
        collaborations=collaborations
    )


# =========================================================
# ADMIN HELPER
# =========================================================

def admin_required():

    if "user_id" not in session:
        return redirect(url_for("admin_login"))

    if session.get("user_role") != "admin":
        return "Access denied. Admin account required.", 403

    return None

# =========================================================
# SEPARATE ADMIN LOGIN
# =========================================================

@app.route("/admin-login", methods=["GET", "POST"])
def admin_login():

    if request.method == "POST":

        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")

        connection = get_database()

        admin = connection.execute("""
            SELECT *
            FROM users
            WHERE email = %s
            AND role = 'admin'
        """, (email,)).fetchone()

        connection.close()

        if not admin:
            return render_template(
                "admin_login.html",
                error="Admin account not found."
            )

        if not check_password_hash(
            admin["password"],
            password
        ):
            return render_template(
                "admin_login.html",
                error="Incorrect admin password."
            )

        session["user_id"] = admin["id"]
        session["user_name"] = admin["name"]
        session["user_email"] = admin["email"]
        session["user_role"] = "admin"

        return redirect(url_for("admin_dashboard"))

    return render_template("admin_login.html")

# =========================================================
# ADMIN DASHBOARD
# =========================================================

@app.route("/admin")
def admin_dashboard():

    access = admin_required()

    if access:
        return access

    connection = get_database()

    u_res = connection.execute("SELECT COUNT(*) FROM users").fetchone()
    total_users = u_res[0] if u_res else 0

    c_res = connection.execute("SELECT COUNT(*) FROM submissions").fetchone()
    total_challenges = c_res[0] if c_res else 0

    p_res = connection.execute("SELECT COUNT(*) FROM university_projects").fetchone()
    total_projects = p_res[0] if p_res else 0

    col_res = connection.execute("SELECT COUNT(*) FROM collaborations").fetchone()
    total_collaborations = col_res[0] if col_res else 0

    # Actual status used when a citizen submits a problem.
    s_res = connection.execute("""
        SELECT COUNT(*)
        FROM submissions
        WHERE status = 'Submitted'
    """).fetchone()
    submitted_challenges = s_res[0] if s_res else 0

    # Actual status used when university accepts.
    a_res = connection.execute("""
        SELECT COUNT(*)
        FROM submissions
        WHERE status = 'Accepted by University'
    """).fetchone()
    accepted_challenges = a_res[0] if a_res else 0

    # Actual status used when university declines.
    d_res = connection.execute("""
        SELECT COUNT(*)
        FROM submissions
        WHERE status = 'Declined by University'
    """).fetchone()
    denied_challenges = d_res[0] if d_res else 0

    pen_res = connection.execute("""
        SELECT COUNT(*)
        FROM collaborations
        WHERE status = 'Pending'
    """).fetchone()
    pending_collaborations = pen_res[0] if pen_res else 0

    ac_res = connection.execute("""
        SELECT COUNT(*)
        FROM collaborations
        WHERE status = 'Accepted'
    """).fetchone()
    accepted_collaborations = ac_res[0] if ac_res else 0

    # Admin messages
    admin_messages = connection.execute("""
        SELECT
            admin_messages.*,
            universities.name AS university_name,
            universities.email AS university_email,
            university_projects.project_title AS project_title
        FROM admin_messages
        LEFT JOIN users AS universities
            ON admin_messages.university_id = universities.id
        LEFT JOIN university_projects
            ON admin_messages.project_id = university_projects.id
        ORDER BY admin_messages.id DESC
    """).fetchall()

    connection.close()

    return render_template(
        "admin_dashboard.html",
        total_users=total_users,
        total_challenges=total_challenges,
        total_projects=total_projects,
        total_collaborations=total_collaborations,
        submitted_challenges=submitted_challenges,
        accepted_challenges=accepted_challenges,
        denied_challenges=denied_challenges,
        pending_collaborations=pending_collaborations,
        accepted_collaborations=accepted_collaborations,
        admin_messages=admin_messages
    )

# =========================================================
# ADMIN - VIEW SENT MESSAGES
# =========================================================

@app.route("/admin/messages")
def admin_messages():

    access = admin_required()

    if access:
        return access

    connection = get_database()

    messages = connection.execute("""
        SELECT
            admin_messages.*,
            universities.name AS university_name,
            universities.email AS university_email,
            university_projects.project_title AS project_title
        FROM admin_messages
        LEFT JOIN users AS universities
            ON admin_messages.university_id = universities.id
        LEFT JOIN university_projects
            ON admin_messages.project_id = university_projects.id
        ORDER BY admin_messages.id DESC
    """).fetchall()

    connection.close()

    return render_template(
        "admin_messages.html",
        messages=messages
    )

# =========================================================
# ADMIN - VIEW ALL CHALLENGES
# =========================================================

@app.route("/admin/challenges")
def admin_challenges():

    access = admin_required()

    if access:
        return access

    connection = get_database()

    challenges = connection.execute("""
        SELECT *
        FROM submissions
        ORDER BY id DESC
    """).fetchall()

    connection.close()

    return render_template(
        "admin_challenges.html",
        challenges=challenges
    )


# =========================================================
# ADMIN - VIEW SINGLE CHALLENGE
# =========================================================

@app.route("/admin/challenge/<int:submission_id>")
def admin_view_challenge(submission_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    challenge = connection.execute("""
        SELECT *
        FROM submissions
        WHERE id = %s
    """, (submission_id,)).fetchone()

    if not challenge:
        connection.close()
        return "Challenge not found.", 404

    connection.close()

    return render_template(
        "admin_challenge_details.html",
        challenge=challenge
    )

# =========================================================
# ADMIN - EDIT CHALLENGE
# =========================================================

@app.route("/admin/challenge/<int:submission_id>/edit", methods=["GET", "POST"])
def admin_edit_challenge(submission_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    challenge = connection.execute("""
        SELECT *
        FROM submissions
        WHERE id = %s
    """, (submission_id,)).fetchone()

    if not challenge:
        connection.close()
        return "Challenge not found.", 404

    if request.method == "POST":

        title = request.form.get("title", "").strip()
        description = request.form.get("description", "").strip()
        category = request.form.get("category", "").strip()
        priority = request.form.get("priority", "").strip()
        district = request.form.get("district", "").strip()
        address = request.form.get("address", "").strip()

        if not title or not description or not category or not priority or not district or not address:
            connection.close()

            return render_template(
                "admin_edit_challenge.html",
                challenge=challenge,
                error="Please fill in all required fields."
            )

        connection.execute("""
            UPDATE submissions
            SET
                title = %s,
                description = %s,
                category = %s,
                priority = %s,
                district = %s,
                address = %s
            WHERE id = %s
        """, (
            title,
            description,
            category,
            priority,
            district,
            address,
            submission_id
        ))

        connection.commit()

        updated_challenge = connection.execute("""
            SELECT *
            FROM submissions
            WHERE id = %s
        """, (submission_id,)).fetchone()

        connection.close()

        return render_template(
            "admin_challenge_details.html",
            challenge=updated_challenge,
            success="Challenge updated successfully."
        )

    connection.close()

    return render_template(
        "admin_edit_challenge.html",
        challenge=challenge
    )


# =========================================================
# ADMIN - DELETE CHALLENGE
# =========================================================

@app.route("/admin/challenge/<int:submission_id>/delete", methods=["POST"])
def admin_delete_challenge(submission_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    challenge = connection.execute("""
        SELECT *
        FROM submissions
        WHERE id = %s
    """, (submission_id,)).fetchone()

    if not challenge:
        connection.close()
        return "Challenge not found.", 404

    # Delete related projects and collaborations
    projects = connection.execute("""
        SELECT id
        FROM university_projects
        WHERE submission_id = %s
    """, (submission_id,)).fetchall()

    for project in projects:
        connection.execute("""
            DELETE FROM collaborations
            WHERE project_id = %s
        """, (project["id"],))

    connection.execute("""
        DELETE FROM university_projects
        WHERE submission_id = %s
    """, (submission_id,))

    # Delete uploaded photo
    if challenge["photo"]:
        photo_path = os.path.join(
            app.config["UPLOAD_FOLDER"],
            challenge["photo"]
        )

        if os.path.exists(photo_path):
            os.remove(photo_path)

    # Delete uploaded video
    if challenge["video"]:
        video_path = os.path.join(
            app.config["UPLOAD_FOLDER"],
            challenge["video"]
        )

        if os.path.exists(video_path):
            os.remove(video_path)

    # Delete challenge
    connection.execute("""
        DELETE FROM submissions
        WHERE id = %s
    """, (submission_id,))

    connection.commit()
    connection.close()

    return redirect(url_for("admin_challenges"))


# =========================================================
# ADMIN - VIEW USERS
# =========================================================

@app.route("/admin/users")
def admin_users():

    access = admin_required()

    if access:
        return access

    connection = get_database()

    users = connection.execute("""
        SELECT
            id,
            name,
            email,
            phone,
            address,
            district,
            role
        FROM users
        ORDER BY id DESC
    """).fetchall()

    connection.close()

    return render_template(
        "admin_users.html",
        users=users
    )


# =========================================================
# ADMIN - VIEW SINGLE USER
# =========================================================

@app.route("/admin/user/<int:user_id>")
def admin_view_user(user_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    user = connection.execute("""
        SELECT
            id,
            name,
            email,
            phone,
            address,
            district,
            role
        FROM users
        WHERE id = %s
    """, (user_id,)).fetchone()

    if not user:
        connection.close()
        return "User not found.", 404

    connection.close()

    return render_template(
        "admin_user_details.html",
        user=user
    )


# =========================================================
# ADMIN - EDIT USER
# =========================================================

@app.route("/admin/user/<int:user_id>/edit", methods=["GET", "POST"])
def admin_edit_user(user_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    user = connection.execute("""
        SELECT *
        FROM users
        WHERE id = %s
    """, (user_id,)).fetchone()

    if not user:
        connection.close()
        return "User not found.", 404

    if request.method == "POST":

        name = request.form.get("name", "").strip()
        email = request.form.get("email", "").strip().lower()
        phone = request.form.get("phone", "").strip()
        address = request.form.get("address", "").strip()
        district = request.form.get("district", "").strip()
        role = request.form.get("role", "").strip()

        allowed_roles = [
            "citizen",
            "university",
            "industry",
            "admin"
        ]

        if not name or not email:
            connection.close()

            return render_template(
                "admin_edit_user.html",
                user=user,
                error="Name and email are required."
            )

        if role not in allowed_roles:
            connection.close()

            return render_template(
                "admin_edit_user.html",
                user=user,
                error="Invalid account type."
            )

        existing_email = connection.execute("""
            SELECT id
            FROM users
            WHERE email = %s
            AND id != %s
        """, (email, user_id)).fetchone()

        if existing_email:
            connection.close()

            return render_template(
                "admin_edit_user.html",
                user=user,
                error="Another account already uses this email."
            )

        connection.execute("""
            UPDATE users
            SET
                name = %s,
                email = %s,
                phone = %s,
                address = %s,
                district = %s,
                role = %s
            WHERE id = %s
        """, (
            name,
            email,
            phone,
            address,
            district,
            role,
            user_id
        ))

        connection.commit()

        updated_user = connection.execute("""
            SELECT *
            FROM users
            WHERE id = %s
        """, (user_id,)).fetchone()

        connection.close()

        return render_template(
            "admin_user_details.html",
            user=updated_user,
            success="User updated successfully."
        )

    connection.close()

    return render_template(
        "admin_edit_user.html",
        user=user
    )


# =========================================================
# ADMIN - DELETE USER
# =========================================================

@app.route("/admin/user/<int:user_id>/delete", methods=["POST"])
def admin_delete_user(user_id):

    access = admin_required()

    if access:
        return access

    # Prevent admin from deleting their own account
    if user_id == session.get("user_id"):
        return "You cannot delete the currently logged-in admin account.", 400

    connection = get_database()

    user = connection.execute("""
        SELECT *
        FROM users
        WHERE id = %s
    """, (user_id,)).fetchone()

    if not user:
        connection.close()
        return "User not found.", 404

    # Delete collaborations involving this user
    connection.execute("""
        DELETE FROM collaborations
        WHERE industry_id = %s
        OR university_id = %s
    """, (user_id, user_id))

    # Delete projects created by this university
    projects = connection.execute("""
        SELECT id
        FROM university_projects
        WHERE university_id = %s
    """, (user_id,)).fetchall()

    for project in projects:

        connection.execute("""
            DELETE FROM collaborations
            WHERE project_id = %s
        """, (project["id"],))

    connection.execute("""
        DELETE FROM university_projects
        WHERE university_id = %s
    """, (user_id,))

    # Delete user
    connection.execute("""
        DELETE FROM users
        WHERE id = %s
    """, (user_id,))

    connection.commit()
    connection.close()

    return redirect(url_for("admin_users"))


# =========================================================
# ADMIN - VIEW UNIVERSITY PROJECTS
# =========================================================

@app.route("/admin/projects")
def admin_projects():

    access = admin_required()

    if access:
        return access

    connection = get_database()

    projects = connection.execute("""
        SELECT
            university_projects.*,

            submissions.title AS challenge_title,
            submissions.description AS challenge_description,
            submissions.category AS challenge_category,
            submissions.priority AS challenge_priority,
            submissions.district AS challenge_district,
            submissions.address AS challenge_address,
            submissions.photo AS challenge_photo,
            submissions.video AS challenge_video,
            submissions.status AS challenge_status,

            users.name AS university_name,
            users.email AS university_email

        FROM university_projects

        LEFT JOIN submissions
            ON university_projects.submission_id = submissions.id

        LEFT JOIN users
            ON university_projects.university_id = users.id

        ORDER BY university_projects.id DESC
    """).fetchall()

    connection.close()

    return render_template(
        "admin_projects.html",
        projects=projects
    )


# =========================================================
# ADMIN - VIEW SINGLE PROJECT
# =========================================================

@app.route("/admin/project/<int:project_id>")
def admin_view_project(project_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    project = connection.execute("""
        SELECT
            university_projects.*,

            submissions.name AS citizen_name,
            submissions.email AS citizen_email,
            submissions.phone AS citizen_phone,
            submissions.address AS citizen_address,
            submissions.district AS citizen_district,
            submissions.title AS challenge_title,
            submissions.description AS challenge_description,
            submissions.category AS challenge_category,
            submissions.priority AS challenge_priority,
            submissions.photo AS challenge_photo,
            submissions.video AS challenge_video,
            submissions.status AS challenge_status,

            university.name AS university_name,
            university.email AS university_email

        FROM university_projects

        LEFT JOIN submissions
            ON university_projects.submission_id = submissions.id

        LEFT JOIN users AS university
            ON university_projects.university_id = university.id

        WHERE university_projects.id = %s
    """, (project_id,)).fetchone()

    if not project:
        connection.close()
        return "Project not found.", 404

    connection.close()

    return render_template(
        "admin_project_details.html",
        project=project
    )

# =========================================================
# ADMIN - EDIT UNIVERSITY PROJECT
# =========================================================

@app.route("/admin/project/<int:project_id>/edit", methods=["GET", "POST"])
def admin_edit_project(project_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    project = connection.execute("""
        SELECT
            university_projects.*,
            submissions.title AS challenge_title,
            submissions.description AS challenge_description,
            users.name AS university_name
        FROM university_projects

        LEFT JOIN submissions
            ON university_projects.submission_id = submissions.id

        LEFT JOIN users
            ON university_projects.university_id = users.id

        WHERE university_projects.id = %s
    """, (project_id,)).fetchone()

    if not project:
        connection.close()
        return "Project not found.", 404

    if request.method == "POST":

        project_title = request.form.get(
            "project_title", ""
        ).strip()

        project_description = request.form.get(
            "project_description", ""
        ).strip()

        faculty_name = request.form.get(
            "faculty_name", ""
        ).strip()

        student_team = request.form.get(
            "student_team", ""
        ).strip()

        industry_partner = request.form.get(
            "industry_partner", ""
        ).strip()

        status = request.form.get(
            "status", ""
        ).strip()

        allowed_statuses = [
            "Planning",
            "Team Formed",
            "Prototype",
            "Testing",
            "Implementation",
            "Completed"
        ]

        if status not in allowed_statuses:
            status = "Planning"

        if not project_title:
            connection.close()

            return render_template(
                "admin_edit_project.html",
                project=project,
                error="Project title is required."
            )

        connection.execute("""
            UPDATE university_projects
            SET
                project_title = %s,
                project_description = %s,
                faculty_name = %s,
                student_team = %s,
                industry_partner = %s,
                status = %s
            WHERE id = %s
        """, (
            project_title,
            project_description,
            faculty_name,
            student_team,
            industry_partner,
            status,
            project_id
        ))

        connection.commit()

        updated_project = connection.execute("""
            SELECT
                university_projects.*,
                submissions.title AS challenge_title,
                submissions.description AS challenge_description,
                users.name AS university_name
            FROM university_projects

            LEFT JOIN submissions
                ON university_projects.submission_id = submissions.id

            LEFT JOIN users
                ON university_projects.university_id = users.id

            WHERE university_projects.id = %s
        """, (project_id,)).fetchone()

        connection.close()

        return render_template(
            "admin_project_details.html",
            project=updated_project,
            success="University project updated successfully."
        )

    connection.close()

    return render_template(
        "admin_edit_project.html",
        project=project
    )

# =========================================================
# ADMIN - SEND MESSAGE TO UNIVERSITY
# =========================================================

@app.route("/admin/message/university/<int:university_id>/<int:project_id>", methods=["GET", "POST"])
def admin_message_university(university_id, project_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    university = connection.execute("""
        SELECT id, name, email
        FROM users
        WHERE id = %s AND role = 'university'
    """, (university_id,)).fetchone()

    if not university:
        connection.close()
        return "University not found.", 404

    if request.method == "POST":

        subject = request.form.get("subject", "").strip()
        message = request.form.get("message", "").strip()

        if not subject or not message:
            connection.close()
            return "Subject and message are required.", 400

        connection.execute("""
            INSERT INTO admin_messages
            (
                admin_id,
                university_id,
                project_id,
                subject,
                message
            )
            VALUES (%s, %s, %s, %s, %s)
        """, (
            session.get("user_id"),
            university_id,
            project_id,
            subject,
            message
        ))

        connection.commit()
        connection.close()

        return redirect(url_for("admin_dashboard"))

    connection.close()

    return render_template(
    "admin_message_university.html",
    university=university,
    project_id=project_id
)

# =========================================================
# ADMIN - DELETE UNIVERSITY PROJECT
# =========================================================

@app.route("/admin/project/<int:project_id>/delete", methods=["POST"])
def admin_delete_project(project_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    project = connection.execute("""
        SELECT id
        FROM university_projects
        WHERE id = %s
    """, (project_id,)).fetchone()

    if not project:
        connection.close()
        return "Project not found.", 404

    connection.execute("""
        DELETE FROM collaborations
        WHERE project_id = %s
    """, (project_id,))

    connection.execute("""
        DELETE FROM university_projects
        WHERE id = %s
    """, (project_id,))

    connection.commit()
    connection.close()

    return redirect(url_for("admin_projects"))


# =========================================================
# ADMIN - VIEW COLLABORATIONS
# =========================================================

@app.route("/admin/collaborations")
def admin_collaborations():

    access = admin_required()

    if access:
        return access

    connection = get_database()

    collaborations = connection.execute("""
        SELECT
            collaborations.*,

            university_projects.project_title AS project_title,

            university.name AS university_name,
            university.email AS university_email,

            industry.name AS industry_name,
            industry.email AS industry_email

        FROM collaborations

        LEFT JOIN university_projects
            ON collaborations.project_id = university_projects.id

        LEFT JOIN users AS university
            ON collaborations.university_id = university.id

        LEFT JOIN users AS industry
            ON collaborations.industry_id = industry.id

        ORDER BY collaborations.id DESC
    """).fetchall()

    connection.close()

    return render_template(
        "admin_collaborations.html",
        collaborations=collaborations
    )


# =========================================================
# ADMIN - VIEW SINGLE COLLABORATION
# =========================================================

@app.route("/admin/collaboration/<int:collaboration_id>")
def admin_view_collaboration(collaboration_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    collaboration = connection.execute("""
        SELECT
            collaborations.*,

            university_projects.project_title AS project_title,

            university.name AS university_name,
            university.email AS university_email,

            industry.name AS industry_name,
            industry.email AS industry_email

        FROM collaborations

        LEFT JOIN university_projects
            ON collaborations.project_id = university_projects.id

        LEFT JOIN users AS university
            ON collaborations.university_id = university.id

        LEFT JOIN users AS industry
            ON collaborations.industry_id = industry.id

        WHERE collaborations.id = %s
    """, (collaboration_id,)).fetchone()

    if not collaboration:
        connection.close()
        return "Collaboration not found.", 404

    connection.close()

    return render_template(
        "admin_collaboration_details.html",
        collaboration=collaboration
    )


# =========================================================
# ADMIN - EDIT COLLABORATION
# =========================================================

@app.route(
    "/admin/collaboration/<int:collaboration_id>/edit",
    methods=["GET", "POST"]
)
def admin_edit_collaboration(collaboration_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    collaboration = connection.execute("""
        SELECT *
        FROM collaborations
        WHERE id = %s
    """, (collaboration_id,)).fetchone()

    if not collaboration:
        connection.close()
        return "Collaboration not found.", 404

    if request.method == "POST":

        message = request.form.get(
            "message", ""
        ).strip()

        status = request.form.get(
            "status", ""
        ).strip()

        allowed_statuses = [
            "Pending",
            "Accepted",
            "Rejected"
        ]

        if status not in allowed_statuses:
            connection.close()

            return render_template(
                "admin_edit_collaboration.html",
                collaboration=collaboration,
                error="Invalid collaboration status."
            )

        connection.execute("""
            UPDATE collaborations
            SET
                message = %s,
                status = %s
            WHERE id = %s
        """, (
            message,
            status,
            collaboration_id
        ))

        connection.commit()

        updated_collaboration = connection.execute("""
            SELECT
                collaborations.*,

                university_projects.project_title AS project_title,

                university.name AS university_name,
                university.email AS university_email,

                industry.name AS industry_name,
                industry.email AS industry_email

            FROM collaborations

            LEFT JOIN university_projects
                ON collaborations.project_id = university_projects.id

            LEFT JOIN users AS university
                ON collaborations.university_id = university.id

            LEFT JOIN users AS industry
                ON collaborations.industry_id = industry.id

            WHERE collaborations.id = %s
        """, (collaboration_id,)).fetchone()

        connection.close()

        return render_template(
            "admin_collaboration_details.html",
            collaboration=updated_collaboration,
            success="Collaboration updated successfully."
        )

    connection.close()

    return render_template(
        "admin_edit_collaboration.html",
        collaboration=collaboration
    )


# =========================================================
# ADMIN - DELETE COLLABORATION
# =========================================================

@app.route(
    "/admin/collaboration/<int:collaboration_id>/delete",
    methods=["POST"]
)
def admin_delete_collaboration(collaboration_id):

    access = admin_required()

    if access:
        return access

    connection = get_database()

    collaboration = connection.execute("""
        SELECT id
        FROM collaborations
        WHERE id = %s
    """, (collaboration_id,)).fetchone()

    if not collaboration:
        connection.close()
        return "Collaboration not found.", 404

    connection.execute("""
        DELETE FROM collaborations
        WHERE id = %s
    """, (collaboration_id,))

    connection.commit()
    connection.close()

    return redirect(url_for("admin_collaborations"))


# =========================================================
# RUN APPLICATION
# =========================================================

if __name__ == "__main__":
    app.run(debug=True)


